/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/attivita` | `/attivita`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/corsi` | `/corsi`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/legale` | `/legale`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tessera` | `/tessera`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/attivita` | `/attivita`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/corsi` | `/corsi`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/legale` | `/legale`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/tessera` | `/tessera`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/attivita${`?${string}` | `#${string}` | ''}` | `/attivita${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/corsi${`?${string}` | `#${string}` | ''}` | `/corsi${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/legale${`?${string}` | `#${string}` | ''}` | `/legale${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/tessera${`?${string}` | `#${string}` | ''}` | `/tessera${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/attivita` | `/attivita`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/corsi` | `/corsi`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/legale` | `/legale`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/tessera` | `/tessera`; params?: Router.UnknownInputParams; };
    }
  }
}
